// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return firebaseWebConfig;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions firebaseWebConfig = FirebaseOptions(
      apiKey: "AIzaSyCxyJXpHxmfxYvYxTKEFO6rshXrwpbNFwQ",
      authDomain: "famous-statements.firebaseapp.com",
      databaseURL: "https://famous-statements.firebaseio.com",
      projectId: "famous-statements",
      storageBucket: "famous-statements.appspot.com",
      messagingSenderId: "215424509556",
      appId: "1:215424509556:web:3bc444833081b3ef8c1321",
      measurementId: "G-JRLTLTB6FG");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSxxt8b2UtBIPFoNngtKRfjiE5FzHTVrk',
    appId: '1:215424509556:android:c2e79504c6cb3a268c1321',
    messagingSenderId: '215424509556',
    projectId: 'famous-statements',
    databaseURL: 'https://famous-statements.firebaseio.com',
    storageBucket: 'famous-statements.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkSGKNV8t9OLHUN3T9V4uQQ6XXxtxuJ0g',
    appId: '1:215424509556:ios:509292e1af2c7c0a8c1321',
    messagingSenderId: '215424509556',
    projectId: 'famous-statements',
    databaseURL: 'https://famous-statements.firebaseio.com',
    storageBucket: 'famous-statements.appspot.com',
    iosClientId: '215424509556-g0i2do638sbu6fdrsjf9qje8s66lbugd.apps.googleusercontent.com',
    iosBundleId: 'com.armenia.famousstatements',
  );
}
